### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CyrilBaah** [CyrilBaah/fitnesstracker#14]
- Add PR template
- Add Contributor guide

**Comment by vigneshs-dev** [comment]
Hi @CyrilBaah ,
I want to create the documentation for Pull Request template and contributor guide. Can you please assign this to me?

**Comment by CyrilBaah** [comment]
Hello @vigneshs-dev, 
A sample has been added go ahead, make modifications and contribute.

[PULL_REQUEST_TEMPLATE.md](https://github.com/CyrilBaah/fitnesstracker/blob/main/.github/workflows/PULL_REQUEST_TEMPLATE.md)
[CONTRIBUTOR](https://github.com/CyrilBaah/fitnesstracker/blob/main/CONTRIBUTOR.md)

**Comment by mohit-1710** [comment]
@vigneshs-dev please assign this issue to me , I would love to work on it .

**Comment by CyrilBaah** [comment]
Hi @vigneshs-dev, 
This issue has been worked on however, you may go through additional contributions are warmly welcome
