### ISSUE TITLE
Not able to run locally

### ISSUE THREAD

**Issue by vigneshs-dev** [CyrilBaah/fitnesstracker#16]
Hi @CyrilBaah ,
I tried to run your project locally by following the steps given in the README.md file. The Fourth step :

```
 docker-compose build up
```

is not working. So, I used the below command to run the docker file:

```
docker-compose up
```

After running that command also there are some errors which block the app from running. Can you please update the steps to run the project locally?

**Comment by CyrilBaah** [comment]
Hello @vigneshs-dev,
Thank you for identifying this, the guide has been updated which can be accessed [here](https://github.com/CyrilBaah/fitnesstracker?tab=readme-ov-file#how-to-set-up-locally).  Feel free to ask any questions or share contributions. Once again much appreciation.
